# Starship prompt configuration
# https://starship.rs/config/

format = """
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$rust\
$line_break\
$character"""

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold cyan"

[git_branch]
format = "[$branch]($style) "
style = "bold purple"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "bold red"

[python]
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '
style = "yellow"
symbol = ""

[nodejs]
format = "[$symbol($version)]($style) "
style = "green"
symbol = ""

[rust]
format = "[$symbol($version)]($style) "
style = "red"
symbol = ""

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vimcmd_symbol = "[<](bold green)"
